# Configuration du Product Service
server:
  port: 8081
  servlet:
    context-path: /api/products

spring:
  application:
    name: product-service
  
  # Configuration MongoDB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productdb
      # Optionnel : authentification
      # username: admin
      # password: password
      # authentication-database: admin
  
  # Configuration RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password123
    virtual-host: /
  
  security:
    # Configuration pour JWT
    jwt:
      secret: mySecretKey123456789012345678901234567890
      expiration: 86400000 # 24 heures en millisecondes

# Configuration des logs
logging:
  level:
    com.microcommerce.productservice: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator endpoints pour le monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always